// Code generated by protoc-gen-gorums. DO NOT EDIT.
// versions:
// 	protoc-gen-gorums v0.10.0-devel
// 	protoc            v6.33.2
// source: tls/tls.proto

package tls

import (
	gorums "github.com/relab/gorums"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = gorums.EnforceVersion(10 - gorums.MinVersion)
	// Verify that the gorums runtime is sufficiently up-to-date.
	_ = gorums.EnforceVersion(gorums.MaxVersion - 10)
)

// Type aliases for important Gorums types to make them more accessible
// from user code already interacting with the generated code.
type (
	Configuration = gorums.Configuration
	Manager       = gorums.Manager
	Node          = gorums.Node
)

// Use the aliased types to add them to the reserved identifiers list.
// This prevents users from defining message types with these names.
var (
	_ = (*Configuration)(nil)
	_ = (*Manager)(nil)
	_ = (*Node)(nil)
)

// NewManager returns a new Manager for managing connection to nodes added
// to the manager. This function accepts manager options used to configure
// various aspects of the manager.
func NewManager(opts ...gorums.ManagerOption) *Manager {
	return gorums.NewManager(opts...)
}

// NewConfiguration returns a configuration based on the provided list of nodes.
// Nodes can be supplied using WithNodeMap or WithNodeList, or WithNodeIDs.
// A new configuration can also be created from an existing configuration,
// using the And, WithNewNodes, Except, and WithoutNodes methods.
func NewConfiguration(mgr *Manager, opt gorums.NodeListOption) (Configuration, error) {
	return gorums.NewConfiguration(mgr, opt)
}

// NewConfig returns a new [Configuration] based on the provided [gorums.Option]s.
// It accepts exactly one [gorums.NodeListOption] and multiple [gorums.ManagerOption]s.
// You may use this function to create the initial configuration for a new manager.
//
// Example:
//
//		cfg, err := NewConfig(
//		    gorums.WithNodeList([]string{"localhost:8080", "localhost:8081", "localhost:8082"}),
//	        gorums.WithDialOptions(grpc.WithTransportCredentials(insecure.NewCredentials())),
//		)
//
// This is a convenience function for creating a configuration without explicitly
// creating a manager first. However, the manager can be accessed using the
// [Configuration.Manager] method. This method should only be used once since it
// creates a new manager; if a manager already exists, use [NewConfiguration]
// instead, and provide the existing manager as the first argument.
func NewConfig(opts ...gorums.Option) (Configuration, error) {
	return gorums.NewConfig(opts...)
}

// TestTLS is an RPC call invoked on the node in ctx.
func TestTLS(ctx *gorums.NodeContext, in *Request) (resp *Response, err error) {
	res, err := gorums.RPCCall(ctx, in, "tls.TLS.TestTLS")
	if err != nil {
		return nil, err
	}
	return res.(*Response), err
}

// TLS is the server-side API for the TLS Service
type TLSServer interface {
	TestTLS(ctx gorums.ServerCtx, request *Request) (response *Response, err error)
}

func RegisterTLSServer(srv *gorums.Server, impl TLSServer) {
	srv.RegisterHandler("tls.TLS.TestTLS", func(ctx gorums.ServerCtx, in *gorums.Message) (*gorums.Message, error) {
		req := gorums.AsProto[*Request](in)
		resp, err := impl.TestTLS(ctx, req)
		return gorums.NewResponseMessage(in.GetMetadata(), resp), err
	})
}
