// DO NOT EDIT. Generated by 'gorums' plugin for protoc-gen-go
// Source file to edit is: calltype_multicast_tmpl

package dev

import "golang.org/x/net/context"

/* Exported types and methods for multicast method WriteAsync */

// WriteAsync is a one-way multicast call on all nodes in configuration c,
// using the same argument arg. The call is asynchronous and has no return value.
func (c *Configuration) WriteAsync(ctx context.Context, arg *State) error {
	return c.writeAsync(ctx, arg)
}

/* Unexported types and methods for multicast method WriteAsync */

func (c *Configuration) writeAsync(ctx context.Context, arg *State) error {
	for _, node := range c.nodes {
		go func(n *Node) {
			err := n.WriteAsyncClient.Send(arg)
			if err == nil {
				return
			}
			if c.mgr.logger != nil {
				c.mgr.logger.Printf("%d: writeAsync stream send error: %v", n.id, err)
			}
		}(node)
	}

	return nil
}
