// DO NOT EDIT. Generated by 'gorums' plugin for protoc-gen-go
// Source file to edit is: qspec_tmpl

package dev

// QuorumSpec is the interface that wraps every quorum function.
type QuorumSpec interface {

	// ReadCorrectableQF is the quorum function for the ReadCorrectable
	// correctable quorum call method.
	ReadCorrectableQF(replies []*Reply) (*Reply, int, bool)

	// ReadCorrectablePrelimCorrectablePrelimQF is the quorum function for the ReadCorrectablePrelim
	// correctable prelim quourm call method.
	ReadCorrectablePrelimCorrectablePrelimQF(replies []*Reply) (*Reply, int, bool)

	// ReadQCQF is the quorum function for the ReadQC
	// quorum call method.
	ReadQCQF(replies []*Reply) (*Reply, bool)

	// ReadQCCustomReturnQF is the quorum function for the ReadQCCustomReturn
	// quorum call method.
	ReadQCCustomReturnQF(replies []*Reply) (*Reply, bool)

	// ReadQCFutureQF is the quorum function for the ReadQCFuture
	// quorum call method.
	ReadQCFutureQF(replies []*Reply) (*Reply, bool)

	// WriteQCPerNodeQF is the quorum function for the WriteQCPerNode
	// quorum call method.
	WriteQCPerNodeQF(replies []*WriteResp) (*WriteResp, bool)

	// WriteQCWithReqQF is the quorum function for the WriteQCWithReq
	// quorum call method.
	WriteQCWithReqQF(req *Reply, replies []*WriteResp) (*WriteResp, bool)
}
