// Test to benchmark quorum functions with and without the request parameter.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: broadcast/broadcast.proto

package broadcast

import (
	_ "github.com/relab/gorums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=From,proto3" json:"From,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_broadcast_broadcast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_broadcast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_broadcast_broadcast_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Request) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int64                  `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
	Replies       int64                  `protobuf:"varint,2,opt,name=Replies,proto3" json:"Replies,omitempty"`
	From          string                 `protobuf:"bytes,3,opt,name=From,proto3" json:"From,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_broadcast_broadcast_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_broadcast_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_broadcast_broadcast_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *Response) GetReplies() int64 {
	if x != nil {
		return x.Replies
	}
	return 0
}

func (x *Response) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_broadcast_broadcast_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_broadcast_broadcast_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_broadcast_broadcast_proto_rawDescGZIP(), []int{2}
}

var File_broadcast_broadcast_proto protoreflect.FileDescriptor

const file_broadcast_broadcast_proto_rawDesc = "" +
	"\n" +
	"\x19broadcast/broadcast.proto\x12\tbroadcast\x1a\fgorums.proto\"3\n" +
	"\aRequest\x12\x14\n" +
	"\x05Value\x18\x01 \x01(\x03R\x05Value\x12\x12\n" +
	"\x04From\x18\x02 \x01(\tR\x04From\"P\n" +
	"\bResponse\x12\x16\n" +
	"\x06Result\x18\x01 \x01(\x03R\x06Result\x12\x18\n" +
	"\aReplies\x18\x02 \x01(\x03R\aReplies\x12\x12\n" +
	"\x04From\x18\x03 \x01(\tR\x04From\"\a\n" +
	"\x05Empty2\x82\t\n" +
	"\x10BroadcastService\x12;\n" +
	"\n" +
	"QuorumCall\x12\x12.broadcast.Request\x1a\x13.broadcast.Response\"\x04\xa0\xb5\x18\x01\x12L\n" +
	"\x17QuorumCallWithBroadcast\x12\x12.broadcast.Request\x1a\x13.broadcast.Response\"\b\xa0\xb5\x18\x01\x90\xb8\x18\x01\x12H\n" +
	"\x17QuorumCallWithMulticast\x12\x12.broadcast.Request\x1a\x13.broadcast.Response\"\x04\xa0\xb5\x18\x01\x127\n" +
	"\tMulticast\x12\x12.broadcast.Request\x1a\x10.broadcast.Empty\"\x04\x98\xb5\x18\x01\x12C\n" +
	"\x15MulticastIntermediate\x12\x12.broadcast.Request\x1a\x10.broadcast.Empty\"\x04\x98\xb5\x18\x01\x12>\n" +
	"\rBroadcastCall\x12\x12.broadcast.Request\x1a\x13.broadcast.Response\"\x04\xb0\xb5\x18\x01\x12C\n" +
	"\x15BroadcastIntermediate\x12\x12.broadcast.Request\x1a\x10.broadcast.Empty\"\x04\x90\xb8\x18\x01\x127\n" +
	"\tBroadcast\x12\x12.broadcast.Request\x1a\x10.broadcast.Empty\"\x04\x90\xb8\x18\x01\x12E\n" +
	"\x14BroadcastCallForward\x12\x12.broadcast.Request\x1a\x13.broadcast.Response\"\x04\xb0\xb5\x18\x01\x12@\n" +
	"\x0fBroadcastCallTo\x12\x12.broadcast.Request\x1a\x13.broadcast.Response\"\x04\xb0\xb5\x18\x01\x12A\n" +
	"\x13BroadcastToResponse\x12\x12.broadcast.Request\x1a\x10.broadcast.Empty\"\x04\x90\xb8\x18\x01\x127\n" +
	"\x06Search\x12\x12.broadcast.Request\x1a\x13.broadcast.Response\"\x04\xb0\xb5\x18\x01\x12@\n" +
	"\x0fLongRunningTask\x12\x12.broadcast.Request\x1a\x13.broadcast.Response\"\x04\xb0\xb5\x18\x01\x127\n" +
	"\x06GetVal\x12\x12.broadcast.Request\x1a\x13.broadcast.Response\"\x04\xb0\xb5\x18\x01\x126\n" +
	"\x05Order\x12\x12.broadcast.Request\x1a\x13.broadcast.Response\"\x04\xb0\xb5\x18\x01\x128\n" +
	"\n" +
	"PrePrepare\x12\x12.broadcast.Request\x1a\x10.broadcast.Empty\"\x04\x90\xb8\x18\x01\x125\n" +
	"\aPrepare\x12\x12.broadcast.Request\x1a\x10.broadcast.Empty\"\x04\x90\xb8\x18\x01\x124\n" +
	"\x06Commit\x12\x12.broadcast.Request\x1a\x10.broadcast.Empty\"\x04\x90\xb8\x18\x01B)Z'github.com/relab/gorums/tests/broadcastb\x06proto3"

var (
	file_broadcast_broadcast_proto_rawDescOnce sync.Once
	file_broadcast_broadcast_proto_rawDescData []byte
)

func file_broadcast_broadcast_proto_rawDescGZIP() []byte {
	file_broadcast_broadcast_proto_rawDescOnce.Do(func() {
		file_broadcast_broadcast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_broadcast_broadcast_proto_rawDesc), len(file_broadcast_broadcast_proto_rawDesc)))
	})
	return file_broadcast_broadcast_proto_rawDescData
}

var file_broadcast_broadcast_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_broadcast_broadcast_proto_goTypes = []any{
	(*Request)(nil),  // 0: broadcast.Request
	(*Response)(nil), // 1: broadcast.Response
	(*Empty)(nil),    // 2: broadcast.Empty
}
var file_broadcast_broadcast_proto_depIdxs = []int32{
	0,  // 0: broadcast.BroadcastService.QuorumCall:input_type -> broadcast.Request
	0,  // 1: broadcast.BroadcastService.QuorumCallWithBroadcast:input_type -> broadcast.Request
	0,  // 2: broadcast.BroadcastService.QuorumCallWithMulticast:input_type -> broadcast.Request
	0,  // 3: broadcast.BroadcastService.Multicast:input_type -> broadcast.Request
	0,  // 4: broadcast.BroadcastService.MulticastIntermediate:input_type -> broadcast.Request
	0,  // 5: broadcast.BroadcastService.BroadcastCall:input_type -> broadcast.Request
	0,  // 6: broadcast.BroadcastService.BroadcastIntermediate:input_type -> broadcast.Request
	0,  // 7: broadcast.BroadcastService.Broadcast:input_type -> broadcast.Request
	0,  // 8: broadcast.BroadcastService.BroadcastCallForward:input_type -> broadcast.Request
	0,  // 9: broadcast.BroadcastService.BroadcastCallTo:input_type -> broadcast.Request
	0,  // 10: broadcast.BroadcastService.BroadcastToResponse:input_type -> broadcast.Request
	0,  // 11: broadcast.BroadcastService.Search:input_type -> broadcast.Request
	0,  // 12: broadcast.BroadcastService.LongRunningTask:input_type -> broadcast.Request
	0,  // 13: broadcast.BroadcastService.GetVal:input_type -> broadcast.Request
	0,  // 14: broadcast.BroadcastService.Order:input_type -> broadcast.Request
	0,  // 15: broadcast.BroadcastService.PrePrepare:input_type -> broadcast.Request
	0,  // 16: broadcast.BroadcastService.Prepare:input_type -> broadcast.Request
	0,  // 17: broadcast.BroadcastService.Commit:input_type -> broadcast.Request
	1,  // 18: broadcast.BroadcastService.QuorumCall:output_type -> broadcast.Response
	1,  // 19: broadcast.BroadcastService.QuorumCallWithBroadcast:output_type -> broadcast.Response
	1,  // 20: broadcast.BroadcastService.QuorumCallWithMulticast:output_type -> broadcast.Response
	2,  // 21: broadcast.BroadcastService.Multicast:output_type -> broadcast.Empty
	2,  // 22: broadcast.BroadcastService.MulticastIntermediate:output_type -> broadcast.Empty
	1,  // 23: broadcast.BroadcastService.BroadcastCall:output_type -> broadcast.Response
	2,  // 24: broadcast.BroadcastService.BroadcastIntermediate:output_type -> broadcast.Empty
	2,  // 25: broadcast.BroadcastService.Broadcast:output_type -> broadcast.Empty
	1,  // 26: broadcast.BroadcastService.BroadcastCallForward:output_type -> broadcast.Response
	1,  // 27: broadcast.BroadcastService.BroadcastCallTo:output_type -> broadcast.Response
	2,  // 28: broadcast.BroadcastService.BroadcastToResponse:output_type -> broadcast.Empty
	1,  // 29: broadcast.BroadcastService.Search:output_type -> broadcast.Response
	1,  // 30: broadcast.BroadcastService.LongRunningTask:output_type -> broadcast.Response
	1,  // 31: broadcast.BroadcastService.GetVal:output_type -> broadcast.Response
	1,  // 32: broadcast.BroadcastService.Order:output_type -> broadcast.Response
	2,  // 33: broadcast.BroadcastService.PrePrepare:output_type -> broadcast.Empty
	2,  // 34: broadcast.BroadcastService.Prepare:output_type -> broadcast.Empty
	2,  // 35: broadcast.BroadcastService.Commit:output_type -> broadcast.Empty
	18, // [18:36] is the sub-list for method output_type
	0,  // [0:18] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_broadcast_broadcast_proto_init() }
func file_broadcast_broadcast_proto_init() {
	if File_broadcast_broadcast_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_broadcast_broadcast_proto_rawDesc), len(file_broadcast_broadcast_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_broadcast_broadcast_proto_goTypes,
		DependencyIndexes: file_broadcast_broadcast_proto_depIdxs,
		MessageInfos:      file_broadcast_broadcast_proto_msgTypes,
	}.Build()
	File_broadcast_broadcast_proto = out.File
	file_broadcast_broadcast_proto_goTypes = nil
	file_broadcast_broadcast_proto_depIdxs = nil
}
