package dev

import "github.com/relab/gorums"

// WithQuorumSpec returns a ConfigOption containing the provided QuorumSpec.
func WithQuorumSpec(qspec QuorumSpec) gorums.ConfigOption {
	return qspec
}

// WithNodeMap returns a ConfigOption containing the provided
// mapping from node addresses to application-specific IDs.
func WithNodeMap(idMap map[string]uint32) gorums.ConfigOption {
	return gorums.WithNodeMap(idMap)
}

// WithNodeList returns a ConfigOption containing the provided list of node addresses.
// With this option, node IDs are generated by the Manager.
func WithNodeList(addrs []string) gorums.ConfigOption {
	return gorums.WithNodeList(addrs)
}

// WithNodeIDs returns a ConfigOption containing a list of node IDs.
// This assumes that the provided node IDs have already been registered with the manager.
func WithNodeIDs(ids []uint32) gorums.ConfigOption {
	return gorums.WithNodeIDs(ids)
}
