// Code generated by protoc-gen-gorums. DO NOT EDIT.

package dev

import (
	sync "sync"
)

type internalReadResponse struct {
	nid   uint32
	reply *ReadResponse
	err   error
}

// FutureReadResponse is a future object for processing replies.
type FutureReadResponse struct {
	// the actual reply
	*ReadResponse
	NodeIDs []uint32
	err     error
	c       chan struct{}
}

// CorrectableReadResponse is a correctable object for processing replies.
type CorrectableReadResponse struct {
	mu sync.Mutex
	// the actual reply
	*MyReadResponse
	NodeIDs  []uint32
	level    int
	err      error
	done     bool
	watchers []*struct {
		level int
		ch    chan struct{}
	}
	donech chan struct{}
}

// CorrectableStreamReadResponse is a correctable object for processing replies.
type CorrectableStreamReadResponse struct {
	mu sync.Mutex
	// the actual reply
	*ReadResponse
	NodeIDs  []uint32
	level    int
	err      error
	done     bool
	watchers []*struct {
		level int
		ch    chan struct{}
	}
	donech chan struct{}
}
