// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: storage/proto/storage.proto

package proto

import (
	_ "github.com/relab/gorums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReadRequest is the request message for Read RPCs and Read quorum calls.
type ReadRequest struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key string                 `protobuf:"bytes,1,opt,name=key"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_storage_proto_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReadRequest) GetKey() string {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return ""
}

func (x *ReadRequest) SetKey(v string) {
	x.xxx_hidden_Key = v
}

type ReadRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key string
}

func (b0 ReadRequest_builder) Build() *ReadRequest {
	m0 := &ReadRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	return m0
}

// ReadResponse is the response message for Read RPCs and Read quorum calls.
type ReadResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_OK    bool                   `protobuf:"varint,1,opt,name=OK"`
	xxx_hidden_Value string                 `protobuf:"bytes,2,opt,name=value"`
	xxx_hidden_Time  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_storage_proto_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReadResponse) GetOK() bool {
	if x != nil {
		return x.xxx_hidden_OK
	}
	return false
}

func (x *ReadResponse) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *ReadResponse) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Time
	}
	return nil
}

func (x *ReadResponse) SetOK(v bool) {
	x.xxx_hidden_OK = v
}

func (x *ReadResponse) SetValue(v string) {
	x.xxx_hidden_Value = v
}

func (x *ReadResponse) SetTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_Time = v
}

func (x *ReadResponse) HasTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Time != nil
}

func (x *ReadResponse) ClearTime() {
	x.xxx_hidden_Time = nil
}

type ReadResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	OK    bool
	Value string
	Time  *timestamppb.Timestamp
}

func (b0 ReadResponse_builder) Build() *ReadResponse {
	m0 := &ReadResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_OK = b.OK
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_Time = b.Time
	return m0
}

// WriteRequest is the request message for Write RPCs, Write quorum calls, and Write multicast calls.
type WriteRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key   string                 `protobuf:"bytes,1,opt,name=key"`
	xxx_hidden_Value string                 `protobuf:"bytes,2,opt,name=value"`
	xxx_hidden_Time  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_storage_proto_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WriteRequest) GetKey() string {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return ""
}

func (x *WriteRequest) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *WriteRequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Time
	}
	return nil
}

func (x *WriteRequest) SetKey(v string) {
	x.xxx_hidden_Key = v
}

func (x *WriteRequest) SetValue(v string) {
	x.xxx_hidden_Value = v
}

func (x *WriteRequest) SetTime(v *timestamppb.Timestamp) {
	x.xxx_hidden_Time = v
}

func (x *WriteRequest) HasTime() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Time != nil
}

func (x *WriteRequest) ClearTime() {
	x.xxx_hidden_Time = nil
}

type WriteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key   string
	Value string
	Time  *timestamppb.Timestamp
}

func (b0 WriteRequest_builder) Build() *WriteRequest {
	m0 := &WriteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_Time = b.Time
	return m0
}

// WriteResponse is the response message for Write RPCs and Write quorum calls.
type WriteResponse struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_New bool                   `protobuf:"varint,1,opt,name=new"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_storage_proto_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WriteResponse) GetNew() bool {
	if x != nil {
		return x.xxx_hidden_New
	}
	return false
}

func (x *WriteResponse) SetNew(v bool) {
	x.xxx_hidden_New = v
}

type WriteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	New bool
}

func (b0 WriteResponse_builder) Build() *WriteResponse {
	m0 := &WriteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_New = b.New
	return m0
}

var File_storage_proto_storage_proto protoreflect.FileDescriptor

const file_storage_proto_storage_proto_rawDesc = "" +
	"\n" +
	"\x1bstorage/proto/storage.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fgorums.proto\"\x1f\n" +
	"\vReadRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"d\n" +
	"\fReadResponse\x12\x0e\n" +
	"\x02OK\x18\x01 \x01(\bR\x02OK\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"f\n" +
	"\fWriteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"!\n" +
	"\rWriteResponse\x12\x10\n" +
	"\x03new\x18\x01 \x01(\bR\x03new2\xb2\x02\n" +
	"\aStorage\x124\n" +
	"\aReadRPC\x12\x12.proto.ReadRequest\x1a\x13.proto.ReadResponse\"\x00\x127\n" +
	"\bWriteRPC\x12\x13.proto.WriteRequest\x1a\x14.proto.WriteResponse\"\x00\x127\n" +
	"\x06ReadQC\x12\x12.proto.ReadRequest\x1a\x13.proto.ReadResponse\"\x04\xa0\xb5\x18\x01\x12:\n" +
	"\aWriteQC\x12\x13.proto.WriteRequest\x1a\x14.proto.WriteResponse\"\x04\xa0\xb5\x18\x01\x12C\n" +
	"\x0eWriteMulticast\x12\x13.proto.WriteRequest\x1a\x16.google.protobuf.Empty\"\x04\x98\xb5\x18\x01B5Z.github.com/relab/gorums/examples/storage/proto\x92\x03\x02\b\x02b\beditionsp\xe9\a"

var file_storage_proto_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_storage_proto_storage_proto_goTypes = []any{
	(*ReadRequest)(nil),           // 0: proto.ReadRequest
	(*ReadResponse)(nil),          // 1: proto.ReadResponse
	(*WriteRequest)(nil),          // 2: proto.WriteRequest
	(*WriteResponse)(nil),         // 3: proto.WriteResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_storage_proto_storage_proto_depIdxs = []int32{
	4, // 0: proto.ReadResponse.time:type_name -> google.protobuf.Timestamp
	4, // 1: proto.WriteRequest.time:type_name -> google.protobuf.Timestamp
	0, // 2: proto.Storage.ReadRPC:input_type -> proto.ReadRequest
	2, // 3: proto.Storage.WriteRPC:input_type -> proto.WriteRequest
	0, // 4: proto.Storage.ReadQC:input_type -> proto.ReadRequest
	2, // 5: proto.Storage.WriteQC:input_type -> proto.WriteRequest
	2, // 6: proto.Storage.WriteMulticast:input_type -> proto.WriteRequest
	1, // 7: proto.Storage.ReadRPC:output_type -> proto.ReadResponse
	3, // 8: proto.Storage.WriteRPC:output_type -> proto.WriteResponse
	1, // 9: proto.Storage.ReadQC:output_type -> proto.ReadResponse
	3, // 10: proto.Storage.WriteQC:output_type -> proto.WriteResponse
	5, // 11: proto.Storage.WriteMulticast:output_type -> google.protobuf.Empty
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_storage_proto_storage_proto_init() }
func file_storage_proto_storage_proto_init() {
	if File_storage_proto_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_storage_proto_rawDesc), len(file_storage_proto_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_proto_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_storage_proto_depIdxs,
		MessageInfos:      file_storage_proto_storage_proto_msgTypes,
	}.Build()
	File_storage_proto_storage_proto = out.File
	file_storage_proto_storage_proto_goTypes = nil
	file_storage_proto_storage_proto_depIdxs = nil
}
