// Code generated by protoc-gen-gorums. DO NOT EDIT.
// versions:
// 	protoc-gen-gorums v0.8.0-devel
// 	protoc            v5.29.2
// source: storage/proto/storage.proto

package proto

import (
	context "context"
	fmt "fmt"
	gorums "github.com/relab/gorums"
	encoding "google.golang.org/grpc/encoding"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = gorums.EnforceVersion(8 - gorums.MinVersion)
	// Verify that the gorums runtime is sufficiently up-to-date.
	_ = gorums.EnforceVersion(gorums.MaxVersion - 8)
)

func init() {
	if encoding.GetCodec(gorums.ContentSubtype) == nil {
		encoding.RegisterCodec(gorums.NewCodec())
	}
}

// StorageClient is the client interface for the Storage service.
type StorageClient interface {
	ReadQC(ctx context.Context, in *ReadRequest) (resp *ReadResponse, err error)
	WriteQC(ctx context.Context, in *WriteRequest) (resp *WriteResponse, err error)
	WriteMulticast(ctx context.Context, in *WriteRequest, opts ...gorums.CallOption)
}

// enforce interface compliance
var _ StorageClient = (*StorageConfiguration)(nil)

// StorageNodeClient is the single node client interface for the Storage service.
type StorageNodeClient interface {
	ReadRPC(ctx context.Context, in *ReadRequest) (resp *ReadResponse, err error)
	WriteRPC(ctx context.Context, in *WriteRequest) (resp *WriteResponse, err error)
}

// enforce interface compliance
var _ StorageNodeClient = (*StorageNode)(nil)

// A StorageConfiguration represents a static set of nodes on which quorum remote
// procedure calls may be invoked.
type StorageConfiguration struct {
	gorums.RawConfiguration
	qspec StorageQuorumSpec
	nodes []*StorageNode
} // StorageQuorumSpecFromRaw returns a new StorageQuorumSpec from the given raw configuration and QuorumSpec.
//
// This function may for example be used to "clone" a configuration but install a different QuorumSpec:
//
//	cfg1, err := mgr.NewConfiguration(qspec1, opts...)
//	cfg2 := ConfigurationFromRaw(cfg1.RawConfig, qspec2)
func StorageConfigurationFromRaw(rawCfg gorums.RawConfiguration, qspec StorageQuorumSpec) (*StorageConfiguration, error) {
	// return an error if qspec is nil.
	if qspec == nil {
		return nil, fmt.Errorf("config: missing required QuorumSpec")
	}
	newCfg := &StorageConfiguration{
		RawConfiguration: rawCfg,
		qspec:            qspec,
	}
	// initialize the nodes slice
	newCfg.nodes = make([]*StorageNode, newCfg.Size())
	for i, n := range rawCfg {
		newCfg.nodes[i] = &StorageNode{n}
	}
	return newCfg, nil
}

// Nodes returns a slice of each available node. IDs are returned in the same
// order as they were provided in the creation of the Manager.
//
// NOTE: mutating the returned slice is not supported.
func (c *StorageConfiguration) Nodes() []*StorageNode {
	return c.nodes
}

// And returns a NodeListOption that can be used to create a new configuration combining c and d.
func (c StorageConfiguration) And(d *StorageConfiguration) gorums.NodeListOption {
	return c.RawConfiguration.And(d.RawConfiguration)
}

// Except returns a NodeListOption that can be used to create a new configuration
// from c without the nodes in rm.
func (c StorageConfiguration) Except(rm *StorageConfiguration) gorums.NodeListOption {
	return c.RawConfiguration.Except(rm.RawConfiguration)
}

// StorageManager maintains a connection pool of nodes on
// which quorum calls can be performed.
type StorageManager struct {
	*gorums.RawManager
}

// NewStorageManager returns a new StorageManager for managing connection to nodes added
// to the manager. This function accepts manager options used to configure
// various aspects of the manager.
func NewStorageManager(opts ...gorums.ManagerOption) *StorageManager {
	return &StorageManager{
		RawManager: gorums.NewRawManager(opts...),
	}
} // NewStorageConfiguration returns a StorageConfiguration based on the provided list of nodes (required)
// and a quorum specification
// .
// Nodes can be supplied using WithNodeMap or WithNodeList, or WithNodeIDs.
// A new configuration can also be created from an existing configuration,
// using the And, WithNewNodes, Except, and WithoutNodes methods.
func (m *StorageManager) NewConfiguration(cfg gorums.NodeListOption, qspec StorageQuorumSpec) (c *StorageConfiguration, err error) {
	c = &StorageConfiguration{}
	c.RawConfiguration, err = gorums.NewRawConfiguration(m.RawManager, cfg)
	if err != nil {
		return nil, err
	}
	// return an error if qspec is nil.
	if qspec == nil {
		return nil, fmt.Errorf("config: missing required StorageQuorumSpec")
	}
	c.qspec = qspec
	// initialize the nodes slice
	c.nodes = make([]*StorageNode, c.Size())
	for i, n := range c.RawConfiguration {
		c.nodes[i] = &StorageNode{n}
	}
	return c, nil
}

// Nodes returns a slice of available nodes on this manager.
// IDs are returned in the order they were added at creation of the manager.
func (m *StorageManager) Nodes() []*StorageNode {
	gorumsNodes := m.RawManager.Nodes()
	nodes := make([]*StorageNode, len(gorumsNodes))
	for i, n := range gorumsNodes {
		nodes[i] = &StorageNode{n}
	}
	return nodes
}

// Reference imports to suppress errors if they are not otherwise used.
var _ emptypb.Empty

// WriteMulticast is a quorum call invoked on all nodes in configuration c,
// with the same argument in, and returns a combined result.
func (c *StorageConfiguration) WriteMulticast(ctx context.Context, in *WriteRequest, opts ...gorums.CallOption) {
	cd := gorums.QuorumCallData{
		Message: in,
		Method:  "storage.Storage.WriteMulticast",
	}

	c.RawConfiguration.Multicast(ctx, cd, opts...)
}

// StorageNode holds the node specific methods for the Storage service.
type StorageNode struct {
	*gorums.RawNode
}

// StorageQuorumSpec is the interface of quorum functions for Storage.
type StorageQuorumSpec interface {
	gorums.ConfigOption

	// ReadQCQF is the quorum function for the ReadQC
	// quorum call method. The in parameter is the request object
	// supplied to the ReadQC method at call time, and may or may not
	// be used by the quorum function. If the in parameter is not needed
	// you should implement your quorum function with '_ *ReadRequest'.
	ReadQCQF(in *ReadRequest, replies map[uint32]*ReadResponse) (*ReadResponse, bool)

	// WriteQCQF is the quorum function for the WriteQC
	// quorum call method. The in parameter is the request object
	// supplied to the WriteQC method at call time, and may or may not
	// be used by the quorum function. If the in parameter is not needed
	// you should implement your quorum function with '_ *WriteRequest'.
	WriteQCQF(in *WriteRequest, replies map[uint32]*WriteResponse) (*WriteResponse, bool)
}

// ReadQC executes the Read Quorum Call on a configuration
// of Nodes and returns the most recent value.
func (c *StorageConfiguration) ReadQC(ctx context.Context, in *ReadRequest) (resp *ReadResponse, err error) {
	cd := gorums.QuorumCallData{
		Message: in,
		Method:  "storage.Storage.ReadQC",
	}
	cd.QuorumFunction = func(req protoreflect.ProtoMessage, replies map[uint32]protoreflect.ProtoMessage) (protoreflect.ProtoMessage, bool) {
		r := make(map[uint32]*ReadResponse, len(replies))
		for k, v := range replies {
			r[k] = v.(*ReadResponse)
		}
		return c.qspec.ReadQCQF(req.(*ReadRequest), r)
	}

	res, err := c.RawConfiguration.QuorumCall(ctx, cd)
	if err != nil {
		return nil, err
	}
	return res.(*ReadResponse), err
}

// WriteQC executes the Write Quorum Call on a configuration
// of Nodes and returns true if a majority of Nodes were updated.
func (c *StorageConfiguration) WriteQC(ctx context.Context, in *WriteRequest) (resp *WriteResponse, err error) {
	cd := gorums.QuorumCallData{
		Message: in,
		Method:  "storage.Storage.WriteQC",
	}
	cd.QuorumFunction = func(req protoreflect.ProtoMessage, replies map[uint32]protoreflect.ProtoMessage) (protoreflect.ProtoMessage, bool) {
		r := make(map[uint32]*WriteResponse, len(replies))
		for k, v := range replies {
			r[k] = v.(*WriteResponse)
		}
		return c.qspec.WriteQCQF(req.(*WriteRequest), r)
	}

	res, err := c.RawConfiguration.QuorumCall(ctx, cd)
	if err != nil {
		return nil, err
	}
	return res.(*WriteResponse), err
}

// ReadRPC executes the Read RPC on a single Node
func (n *StorageNode) ReadRPC(ctx context.Context, in *ReadRequest) (resp *ReadResponse, err error) {
	cd := gorums.CallData{
		Message: in,
		Method:  "storage.Storage.ReadRPC",
	}

	res, err := n.RawNode.RPCCall(ctx, cd)
	if err != nil {
		return nil, err
	}
	return res.(*ReadResponse), err
}

// WriteRPC executes the Write RPC on a single Node
func (n *StorageNode) WriteRPC(ctx context.Context, in *WriteRequest) (resp *WriteResponse, err error) {
	cd := gorums.CallData{
		Message: in,
		Method:  "storage.Storage.WriteRPC",
	}

	res, err := n.RawNode.RPCCall(ctx, cd)
	if err != nil {
		return nil, err
	}
	return res.(*WriteResponse), err
}

// Storage is the server-side API for the Storage Service
type StorageServer interface {
	ReadRPC(ctx gorums.ServerCtx, request *ReadRequest) (response *ReadResponse, err error)
	WriteRPC(ctx gorums.ServerCtx, request *WriteRequest) (response *WriteResponse, err error)
	ReadQC(ctx gorums.ServerCtx, request *ReadRequest) (response *ReadResponse, err error)
	WriteQC(ctx gorums.ServerCtx, request *WriteRequest) (response *WriteResponse, err error)
	WriteMulticast(ctx gorums.ServerCtx, request *WriteRequest)
}

func RegisterStorageServer(srv *gorums.Server, impl StorageServer) {
	srv.RegisterHandler("storage.Storage.ReadRPC", func(ctx gorums.ServerCtx, in *gorums.Message, finished chan<- *gorums.Message) {
		req := in.Message.(*ReadRequest)
		defer ctx.Release()
		resp, err := impl.ReadRPC(ctx, req)
		gorums.SendMessage(ctx, finished, gorums.WrapMessage(in.Metadata, resp, err))
	})
	srv.RegisterHandler("storage.Storage.WriteRPC", func(ctx gorums.ServerCtx, in *gorums.Message, finished chan<- *gorums.Message) {
		req := in.Message.(*WriteRequest)
		defer ctx.Release()
		resp, err := impl.WriteRPC(ctx, req)
		gorums.SendMessage(ctx, finished, gorums.WrapMessage(in.Metadata, resp, err))
	})
	srv.RegisterHandler("storage.Storage.ReadQC", func(ctx gorums.ServerCtx, in *gorums.Message, finished chan<- *gorums.Message) {
		req := in.Message.(*ReadRequest)
		defer ctx.Release()
		resp, err := impl.ReadQC(ctx, req)
		gorums.SendMessage(ctx, finished, gorums.WrapMessage(in.Metadata, resp, err))
	})
	srv.RegisterHandler("storage.Storage.WriteQC", func(ctx gorums.ServerCtx, in *gorums.Message, finished chan<- *gorums.Message) {
		req := in.Message.(*WriteRequest)
		defer ctx.Release()
		resp, err := impl.WriteQC(ctx, req)
		gorums.SendMessage(ctx, finished, gorums.WrapMessage(in.Metadata, resp, err))
	})
	srv.RegisterHandler("storage.Storage.WriteMulticast", func(ctx gorums.ServerCtx, in *gorums.Message, _ chan<- *gorums.Message) {
		req := in.Message.(*WriteRequest)
		defer ctx.Release()
		impl.WriteMulticast(ctx, req)
	})
}

type internalReadResponse struct {
	nid   uint32
	reply *ReadResponse
	err   error
}

type internalWriteResponse struct {
	nid   uint32
	reply *WriteResponse
	err   error
}
