// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: oneway/oneway.proto

package oneway

import (
	_ "github.com/relab/gorums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Num uint64                 `protobuf:"varint,1,opt,name=Num"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_oneway_oneway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_oneway_oneway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Request) GetNum() uint64 {
	if x != nil {
		return x.xxx_hidden_Num
	}
	return 0
}

func (x *Request) SetNum(v uint64) {
	x.xxx_hidden_Num = v
}

type Request_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Num uint64
}

func (b0 Request_builder) Build() *Request {
	m0 := &Request{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Num = b.Num
	return m0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_oneway_oneway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_oneway_oneway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Empty_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Empty_builder) Build() *Empty {
	m0 := &Empty{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_oneway_oneway_proto protoreflect.FileDescriptor

const file_oneway_oneway_proto_rawDesc = "" +
	"\n" +
	"\x13oneway/oneway.proto\x12\x06oneway\x1a\fgorums.proto\"\x1b\n" +
	"\aRequest\x12\x10\n" +
	"\x03Num\x18\x01 \x01(\x04R\x03Num\"\a\n" +
	"\x05Empty2\xae\x01\n" +
	"\n" +
	"OnewayTest\x12/\n" +
	"\aUnicast\x12\x0f.oneway.Request\x1a\r.oneway.Empty\"\x04\x90\xb5\x18\x01\x121\n" +
	"\tMulticast\x12\x0f.oneway.Request\x1a\r.oneway.Empty\"\x04\x98\xb5\x18\x01\x12<\n" +
	"\x10MulticastPerNode\x12\x0f.oneway.Request\x1a\r.oneway.Empty\"\b\x98\xb5\x18\x01\xa0\xb6\x18\x01B+Z$github.com/relab/gorums/tests/oneway\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_oneway_oneway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_oneway_oneway_proto_goTypes = []any{
	(*Request)(nil), // 0: oneway.Request
	(*Empty)(nil),   // 1: oneway.Empty
}
var file_oneway_oneway_proto_depIdxs = []int32{
	0, // 0: oneway.OnewayTest.Unicast:input_type -> oneway.Request
	0, // 1: oneway.OnewayTest.Multicast:input_type -> oneway.Request
	0, // 2: oneway.OnewayTest.MulticastPerNode:input_type -> oneway.Request
	1, // 3: oneway.OnewayTest.Unicast:output_type -> oneway.Empty
	1, // 4: oneway.OnewayTest.Multicast:output_type -> oneway.Empty
	1, // 5: oneway.OnewayTest.MulticastPerNode:output_type -> oneway.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_oneway_oneway_proto_init() }
func file_oneway_oneway_proto_init() {
	if File_oneway_oneway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oneway_oneway_proto_rawDesc), len(file_oneway_oneway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oneway_oneway_proto_goTypes,
		DependencyIndexes: file_oneway_oneway_proto_depIdxs,
		MessageInfos:      file_oneway_oneway_proto_msgTypes,
	}.Build()
	File_oneway_oneway_proto = out.File
	file_oneway_oneway_proto_goTypes = nil
	file_oneway_oneway_proto_depIdxs = nil
}
