// Code generated by protoc-gen-gorums. DO NOT EDIT.
// versions:
// 	protoc-gen-gorums v0.10.0-devel
// 	protoc            v6.33.2
// source: oneway/oneway.proto

package oneway

import (
	gorums "github.com/relab/gorums"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = gorums.EnforceVersion(10 - gorums.MinVersion)
	// Verify that the gorums runtime is sufficiently up-to-date.
	_ = gorums.EnforceVersion(gorums.MaxVersion - 10)
)

// Type aliases for important Gorums types to make them more accessible
// from user code already interacting with the generated code.
type (
	Configuration = gorums.Configuration
	Manager       = gorums.Manager
	Node          = gorums.Node
)

// Use the aliased types to add them to the reserved identifiers list.
// This prevents users from defining message types with these names.
var (
	_ = (*Configuration)(nil)
	_ = (*Manager)(nil)
	_ = (*Node)(nil)
)

// NewManager returns a new Manager for managing connection to nodes added
// to the manager. This function accepts manager options used to configure
// various aspects of the manager.
func NewManager(opts ...gorums.ManagerOption) *Manager {
	return gorums.NewManager(opts...)
}

// NewConfiguration returns a configuration based on the provided list of nodes.
// Nodes can be supplied using WithNodeMap or WithNodeList, or WithNodeIDs.
// A new configuration can also be created from an existing configuration,
// using the And, WithNewNodes, Except, and WithoutNodes methods.
func NewConfiguration(mgr *Manager, opt gorums.NodeListOption) (Configuration, error) {
	return gorums.NewConfiguration(mgr, opt)
}

// NewConfig returns a new [Configuration] based on the provided [gorums.Option]s.
// It accepts exactly one [gorums.NodeListOption] and multiple [gorums.ManagerOption]s.
// You may use this function to create the initial configuration for a new manager.
//
// Example:
//
//		cfg, err := NewConfig(
//		    gorums.WithNodeList([]string{"localhost:8080", "localhost:8081", "localhost:8082"}),
//	        gorums.WithDialOptions(grpc.WithTransportCredentials(insecure.NewCredentials())),
//		)
//
// This is a convenience function for creating a configuration without explicitly
// creating a manager first. However, the manager can be accessed using the
// [Configuration.Manager] method. This method should only be used once since it
// creates a new manager; if a manager already exists, use [NewConfiguration]
// instead, and provide the existing manager as the first argument.
func NewConfig(opts ...gorums.Option) (Configuration, error) {
	return gorums.NewConfig(opts...)
}

// Unicast is a unicast call invoked on the node in ctx.
// No reply is returned to the client.
func Unicast(ctx *gorums.NodeContext, in *Request, opts ...gorums.CallOption) error {
	return gorums.Unicast(ctx, in, "oneway.OnewayTest.Unicast", opts...)
}

// Multicast is a multicast call invoked on all nodes in the configuration in ctx.
// Use gorums.MapRequest to send different messages to each node. No replies are collected.
func Multicast(ctx *gorums.ConfigContext, in *Request, opts ...gorums.CallOption) error {
	return gorums.Multicast(ctx, in, "oneway.OnewayTest.Multicast", opts...)
}

// OnewayTest is the server-side API for the OnewayTest Service
type OnewayTestServer interface {
	Unicast(ctx gorums.ServerCtx, request *Request)
	Multicast(ctx gorums.ServerCtx, request *Request)
}

func RegisterOnewayTestServer(srv *gorums.Server, impl OnewayTestServer) {
	srv.RegisterHandler("oneway.OnewayTest.Unicast", func(ctx gorums.ServerCtx, in *gorums.Message) (*gorums.Message, error) {
		req := gorums.AsProto[*Request](in)
		impl.Unicast(ctx, req)
		return nil, nil
	})
	srv.RegisterHandler("oneway.OnewayTest.Multicast", func(ctx gorums.ServerCtx, in *gorums.Message) (*gorums.Message, error) {
		req := gorums.AsProto[*Request](in)
		impl.Multicast(ctx, req)
		return nil, nil
	})
}
