// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ordering/ordering.proto

package ordering

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metadata is sent together with application-specific message types,
// and contains information necessary for Gorums to handle the messages.
type Metadata struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MessageID    uint64                 `protobuf:"varint,1,opt,name=MessageID"`
	xxx_hidden_Method       string                 `protobuf:"bytes,2,opt,name=Method"`
	xxx_hidden_Status       *status.Status         `protobuf:"bytes,3,opt,name=Status"`
	xxx_hidden_BroadcastMsg *BroadcastMsg          `protobuf:"bytes,4,opt,name=BroadcastMsg"`
	xxx_hidden_AuthMsg      *AuthMsg               `protobuf:"bytes,5,opt,name=AuthMsg"`
	xxx_hidden_Entry        *[]*MetadataEntry      `protobuf:"bytes,6,rep,name=Entry"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_ordering_ordering_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_ordering_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Metadata) GetMessageID() uint64 {
	if x != nil {
		return x.xxx_hidden_MessageID
	}
	return 0
}

func (x *Metadata) GetMethod() string {
	if x != nil {
		return x.xxx_hidden_Method
	}
	return ""
}

func (x *Metadata) GetStatus() *status.Status {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *Metadata) GetBroadcastMsg() *BroadcastMsg {
	if x != nil {
		return x.xxx_hidden_BroadcastMsg
	}
	return nil
}

func (x *Metadata) GetAuthMsg() *AuthMsg {
	if x != nil {
		return x.xxx_hidden_AuthMsg
	}
	return nil
}

func (x *Metadata) GetEntry() []*MetadataEntry {
	if x != nil {
		if x.xxx_hidden_Entry != nil {
			return *x.xxx_hidden_Entry
		}
	}
	return nil
}

func (x *Metadata) SetMessageID(v uint64) {
	x.xxx_hidden_MessageID = v
}

func (x *Metadata) SetMethod(v string) {
	x.xxx_hidden_Method = v
}

func (x *Metadata) SetStatus(v *status.Status) {
	x.xxx_hidden_Status = v
}

func (x *Metadata) SetBroadcastMsg(v *BroadcastMsg) {
	x.xxx_hidden_BroadcastMsg = v
}

func (x *Metadata) SetAuthMsg(v *AuthMsg) {
	x.xxx_hidden_AuthMsg = v
}

func (x *Metadata) SetEntry(v []*MetadataEntry) {
	x.xxx_hidden_Entry = &v
}

func (x *Metadata) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *Metadata) HasBroadcastMsg() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BroadcastMsg != nil
}

func (x *Metadata) HasAuthMsg() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AuthMsg != nil
}

func (x *Metadata) ClearStatus() {
	x.xxx_hidden_Status = nil
}

func (x *Metadata) ClearBroadcastMsg() {
	x.xxx_hidden_BroadcastMsg = nil
}

func (x *Metadata) ClearAuthMsg() {
	x.xxx_hidden_AuthMsg = nil
}

type Metadata_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MessageID    uint64
	Method       string
	Status       *status.Status
	BroadcastMsg *BroadcastMsg
	AuthMsg      *AuthMsg
	Entry        []*MetadataEntry
}

func (b0 Metadata_builder) Build() *Metadata {
	m0 := &Metadata{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MessageID = b.MessageID
	x.xxx_hidden_Method = b.Method
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_BroadcastMsg = b.BroadcastMsg
	x.xxx_hidden_AuthMsg = b.AuthMsg
	x.xxx_hidden_Entry = &b.Entry
	return m0
}

type BroadcastMsg struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_IsBroadcastClient bool                   `protobuf:"varint,1,opt,name=IsBroadcastClient"`
	xxx_hidden_BroadcastID       uint64                 `protobuf:"varint,2,opt,name=BroadcastID"`
	xxx_hidden_SenderAddr        string                 `protobuf:"bytes,3,opt,name=SenderAddr"`
	xxx_hidden_OriginAddr        string                 `protobuf:"bytes,4,opt,name=OriginAddr"`
	xxx_hidden_OriginMethod      string                 `protobuf:"bytes,5,opt,name=OriginMethod"`
	xxx_hidden_OriginDigest      []byte                 `protobuf:"bytes,6,opt,name=OriginDigest"`
	xxx_hidden_OriginSignature   []byte                 `protobuf:"bytes,7,opt,name=OriginSignature"`
	xxx_hidden_OriginPubKey      string                 `protobuf:"bytes,8,opt,name=OriginPubKey"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *BroadcastMsg) Reset() {
	*x = BroadcastMsg{}
	mi := &file_ordering_ordering_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMsg) ProtoMessage() {}

func (x *BroadcastMsg) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_ordering_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BroadcastMsg) GetIsBroadcastClient() bool {
	if x != nil {
		return x.xxx_hidden_IsBroadcastClient
	}
	return false
}

func (x *BroadcastMsg) GetBroadcastID() uint64 {
	if x != nil {
		return x.xxx_hidden_BroadcastID
	}
	return 0
}

func (x *BroadcastMsg) GetSenderAddr() string {
	if x != nil {
		return x.xxx_hidden_SenderAddr
	}
	return ""
}

func (x *BroadcastMsg) GetOriginAddr() string {
	if x != nil {
		return x.xxx_hidden_OriginAddr
	}
	return ""
}

func (x *BroadcastMsg) GetOriginMethod() string {
	if x != nil {
		return x.xxx_hidden_OriginMethod
	}
	return ""
}

func (x *BroadcastMsg) GetOriginDigest() []byte {
	if x != nil {
		return x.xxx_hidden_OriginDigest
	}
	return nil
}

func (x *BroadcastMsg) GetOriginSignature() []byte {
	if x != nil {
		return x.xxx_hidden_OriginSignature
	}
	return nil
}

func (x *BroadcastMsg) GetOriginPubKey() string {
	if x != nil {
		return x.xxx_hidden_OriginPubKey
	}
	return ""
}

func (x *BroadcastMsg) SetIsBroadcastClient(v bool) {
	x.xxx_hidden_IsBroadcastClient = v
}

func (x *BroadcastMsg) SetBroadcastID(v uint64) {
	x.xxx_hidden_BroadcastID = v
}

func (x *BroadcastMsg) SetSenderAddr(v string) {
	x.xxx_hidden_SenderAddr = v
}

func (x *BroadcastMsg) SetOriginAddr(v string) {
	x.xxx_hidden_OriginAddr = v
}

func (x *BroadcastMsg) SetOriginMethod(v string) {
	x.xxx_hidden_OriginMethod = v
}

func (x *BroadcastMsg) SetOriginDigest(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_OriginDigest = v
}

func (x *BroadcastMsg) SetOriginSignature(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_OriginSignature = v
}

func (x *BroadcastMsg) SetOriginPubKey(v string) {
	x.xxx_hidden_OriginPubKey = v
}

type BroadcastMsg_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	IsBroadcastClient bool
	BroadcastID       uint64
	SenderAddr        string
	OriginAddr        string
	OriginMethod      string
	OriginDigest      []byte
	OriginSignature   []byte
	OriginPubKey      string
}

func (b0 BroadcastMsg_builder) Build() *BroadcastMsg {
	m0 := &BroadcastMsg{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_IsBroadcastClient = b.IsBroadcastClient
	x.xxx_hidden_BroadcastID = b.BroadcastID
	x.xxx_hidden_SenderAddr = b.SenderAddr
	x.xxx_hidden_OriginAddr = b.OriginAddr
	x.xxx_hidden_OriginMethod = b.OriginMethod
	x.xxx_hidden_OriginDigest = b.OriginDigest
	x.xxx_hidden_OriginSignature = b.OriginSignature
	x.xxx_hidden_OriginPubKey = b.OriginPubKey
	return m0
}

type AuthMsg struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PublicKey string                 `protobuf:"bytes,1,opt,name=PublicKey"`
	xxx_hidden_Signature []byte                 `protobuf:"bytes,2,opt,name=Signature"`
	xxx_hidden_Sender    string                 `protobuf:"bytes,3,opt,name=Sender"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AuthMsg) Reset() {
	*x = AuthMsg{}
	mi := &file_ordering_ordering_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthMsg) ProtoMessage() {}

func (x *AuthMsg) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_ordering_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthMsg) GetPublicKey() string {
	if x != nil {
		return x.xxx_hidden_PublicKey
	}
	return ""
}

func (x *AuthMsg) GetSignature() []byte {
	if x != nil {
		return x.xxx_hidden_Signature
	}
	return nil
}

func (x *AuthMsg) GetSender() string {
	if x != nil {
		return x.xxx_hidden_Sender
	}
	return ""
}

func (x *AuthMsg) SetPublicKey(v string) {
	x.xxx_hidden_PublicKey = v
}

func (x *AuthMsg) SetSignature(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Signature = v
}

func (x *AuthMsg) SetSender(v string) {
	x.xxx_hidden_Sender = v
}

type AuthMsg_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PublicKey string
	Signature []byte
	Sender    string
}

func (b0 AuthMsg_builder) Build() *AuthMsg {
	m0 := &AuthMsg{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PublicKey = b.PublicKey
	x.xxx_hidden_Signature = b.Signature
	x.xxx_hidden_Sender = b.Sender
	return m0
}

type MetadataEntry struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key   string                 `protobuf:"bytes,1,opt,name=Key"`
	xxx_hidden_Value string                 `protobuf:"bytes,2,opt,name=Value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MetadataEntry) Reset() {
	*x = MetadataEntry{}
	mi := &file_ordering_ordering_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataEntry) ProtoMessage() {}

func (x *MetadataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ordering_ordering_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MetadataEntry) GetKey() string {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return ""
}

func (x *MetadataEntry) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *MetadataEntry) SetKey(v string) {
	x.xxx_hidden_Key = v
}

func (x *MetadataEntry) SetValue(v string) {
	x.xxx_hidden_Value = v
}

type MetadataEntry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key   string
	Value string
}

func (b0 MetadataEntry_builder) Build() *MetadataEntry {
	m0 := &MetadataEntry{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_Value = b.Value
	return m0
}

var File_ordering_ordering_proto protoreflect.FileDescriptor

const file_ordering_ordering_proto_rawDesc = "" +
	"\n" +
	"\x17ordering/ordering.proto\x12\bordering\x1a\x17google/rpc/status.proto\"\x84\x02\n" +
	"\bMetadata\x12\x1c\n" +
	"\tMessageID\x18\x01 \x01(\x04R\tMessageID\x12\x16\n" +
	"\x06Method\x18\x02 \x01(\tR\x06Method\x12*\n" +
	"\x06Status\x18\x03 \x01(\v2\x12.google.rpc.StatusR\x06Status\x12:\n" +
	"\fBroadcastMsg\x18\x04 \x01(\v2\x16.ordering.BroadcastMsgR\fBroadcastMsg\x12+\n" +
	"\aAuthMsg\x18\x05 \x01(\v2\x11.ordering.AuthMsgR\aAuthMsg\x12-\n" +
	"\x05Entry\x18\x06 \x03(\v2\x17.ordering.MetadataEntryR\x05Entry\"\xb4\x02\n" +
	"\fBroadcastMsg\x12,\n" +
	"\x11IsBroadcastClient\x18\x01 \x01(\bR\x11IsBroadcastClient\x12 \n" +
	"\vBroadcastID\x18\x02 \x01(\x04R\vBroadcastID\x12\x1e\n" +
	"\n" +
	"SenderAddr\x18\x03 \x01(\tR\n" +
	"SenderAddr\x12\x1e\n" +
	"\n" +
	"OriginAddr\x18\x04 \x01(\tR\n" +
	"OriginAddr\x12\"\n" +
	"\fOriginMethod\x18\x05 \x01(\tR\fOriginMethod\x12\"\n" +
	"\fOriginDigest\x18\x06 \x01(\fR\fOriginDigest\x12(\n" +
	"\x0fOriginSignature\x18\a \x01(\fR\x0fOriginSignature\x12\"\n" +
	"\fOriginPubKey\x18\b \x01(\tR\fOriginPubKey\"]\n" +
	"\aAuthMsg\x12\x1c\n" +
	"\tPublicKey\x18\x01 \x01(\tR\tPublicKey\x12\x1c\n" +
	"\tSignature\x18\x02 \x01(\fR\tSignature\x12\x16\n" +
	"\x06Sender\x18\x03 \x01(\tR\x06Sender\"7\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value2B\n" +
	"\x06Gorums\x128\n" +
	"\n" +
	"NodeStream\x12\x12.ordering.Metadata\x1a\x12.ordering.Metadata(\x010\x01B'Z github.com/relab/gorums/ordering\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var file_ordering_ordering_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ordering_ordering_proto_goTypes = []any{
	(*Metadata)(nil),      // 0: ordering.Metadata
	(*BroadcastMsg)(nil),  // 1: ordering.BroadcastMsg
	(*AuthMsg)(nil),       // 2: ordering.AuthMsg
	(*MetadataEntry)(nil), // 3: ordering.MetadataEntry
	(*status.Status)(nil), // 4: google.rpc.Status
}
var file_ordering_ordering_proto_depIdxs = []int32{
	4, // 0: ordering.Metadata.Status:type_name -> google.rpc.Status
	1, // 1: ordering.Metadata.BroadcastMsg:type_name -> ordering.BroadcastMsg
	2, // 2: ordering.Metadata.AuthMsg:type_name -> ordering.AuthMsg
	3, // 3: ordering.Metadata.Entry:type_name -> ordering.MetadataEntry
	0, // 4: ordering.Gorums.NodeStream:input_type -> ordering.Metadata
	0, // 5: ordering.Gorums.NodeStream:output_type -> ordering.Metadata
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ordering_ordering_proto_init() }
func file_ordering_ordering_proto_init() {
	if File_ordering_ordering_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ordering_ordering_proto_rawDesc), len(file_ordering_ordering_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ordering_ordering_proto_goTypes,
		DependencyIndexes: file_ordering_ordering_proto_depIdxs,
		MessageInfos:      file_ordering_ordering_proto_msgTypes,
	}.Build()
	File_ordering_ordering_proto = out.File
	file_ordering_ordering_proto_goTypes = nil
	file_ordering_ordering_proto_depIdxs = nil
}
