---
- hosts: servers
  vars:
    srv_port: ":13371"
  tasks:
    - name: Start servers
      shell: $HOME/benchmark --server '{{ srv_port }}' &> /dev/null &
      ignore_errors: yes
      async: 1000
      poll: 0

- hosts: client
  vars:
    bench_args: ""
    srv_port: ":13371"
  tasks:
    - name: Get IP Addresses
      set_fact: nodelist={%for host in groups['servers']%}"{{hostvars[host]['ansible_default_ipv4']['address'] + srv_port }}"{% if not loop.last %},{% endif %}{% endfor %}
      ignore_errors: yes
    - name: Run benchmark
      command: $HOME/benchmark --remotes "{{ nodelist }}" {{ bench_args }}
      register: output
      ignore_errors: yes
    - name: Print results
      debug: msg={{ output.stdout_lines | join('\n') }}

- hosts: servers
  gather_facts: no
  tasks:
    - name: Kill servers
      shell: killall benchmark
      ignore_errors: yes
