// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: mock/mock.proto

package mock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_mock_mock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_mock_mock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_mock_mock_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           string                 `protobuf:"bytes,1,opt,name=val" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_mock_mock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_mock_mock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_mock_mock_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

var File_mock_mock_proto protoreflect.FileDescriptor

const file_mock_mock_proto_rawDesc = "" +
	"\n" +
	"\x0fmock/mock.proto\x12\x04mock\"\x1b\n" +
	"\aRequest\x12\x10\n" +
	"\x03val\x18\x01 \x01(\tR\x03val\"\x1c\n" +
	"\bResponse\x12\x10\n" +
	"\x03val\x18\x01 \x01(\tR\x03valB)Z\"github.com/relab/gorums/tests/mock\x92\x03\x02\b\x02b\beditionsp\xe8\a"

var (
	file_mock_mock_proto_rawDescOnce sync.Once
	file_mock_mock_proto_rawDescData []byte
)

func file_mock_mock_proto_rawDescGZIP() []byte {
	file_mock_mock_proto_rawDescOnce.Do(func() {
		file_mock_mock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mock_mock_proto_rawDesc), len(file_mock_mock_proto_rawDesc)))
	})
	return file_mock_mock_proto_rawDescData
}

var file_mock_mock_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mock_mock_proto_goTypes = []any{
	(*Request)(nil),  // 0: mock.Request
	(*Response)(nil), // 1: mock.Response
}
var file_mock_mock_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mock_mock_proto_init() }
func file_mock_mock_proto_init() {
	if File_mock_mock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mock_mock_proto_rawDesc), len(file_mock_mock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mock_mock_proto_goTypes,
		DependencyIndexes: file_mock_mock_proto_depIdxs,
		MessageInfos:      file_mock_mock_proto_msgTypes,
	}.Build()
	File_mock_mock_proto = out.File
	file_mock_mock_proto_goTypes = nil
	file_mock_mock_proto_depIdxs = nil
}
